nodeLinker: node-modules

enableStrictSsl: false

# unsafe
npmAuthIdent: "${NPM_AUTH_IDENT}"

npmScopes:
  "axenix":
    npmRegistryServer: "${NPM_REGISTRY_SERVER}"

yarnPath: .yarn/releases/yarn-3.6.1.cjs

